### ISSUE TITLE
Notification on Series when BluRay are Out!

### ISSUE THREAD

**Issue by misakitchi** [ShokoAnime/ShokoServer#102]
Here is my problem: I download a serie and i want to know when the BluRay is out
But I don't want to verify each week if BluRay is out...

So if JMM take info of the serie from AniDB, can we ask him to tell us if there is a BluRay version of the episode/serie?

**Comment by jmediamanager** [comment]
Hi, yes I definitely wanted this feature and I something similar where I show missing episodes from groups that you are already collecting.

The problem is that AniDB API doesn't actually provide the information we need.
It provides episodes by each group, but it doesn't differentiate video source/quality as part of that information.
e.g. It will show Doki, eps 1-13
But not whether they are the original TV, or the subsequent Blu-Ray

As suggested above, I also use ShanaProject to auto download the Blu-Ray's I want.
Combined with the custom tags in JMM, you can keep track of which Blu-Rays you are waiting for.
Not ideal for now, but it is fairly reliable.

I have also logged a request to extend the API here
http://anidb.net/perl-bin/animedb.pl?show=cmt&id=54671

**Comment by misakitchi** [comment]
Its too bad that i don't understand the response of deridiot on anidb...
Why they can't do it?
When i go to the detail of an episode we can see the source for each file: TV, www or DB... so why they say they dont have the info? i don't understand... :(

**Comment by maxpiva** [comment]
Could we wrap this around the ANIDB File  and GROUPSTATUS command, ANIDB File command has quality.

The logic will be, get GROUPS from anime, (Completed)
foreach GROUP get last episode with ANIDB File, if some episode has bluray, then bluray is available.

**Comment by jmediamanager** [comment]
This might possibly work, but would almost certainly be classified as leeching and get a ban.

**Comment by ElementalCrisis** [comment]
Im not sure if this is possible but what about a periodic download of the groups and the files they've released that's either stored locally our via the web cache that JMM checks against? That way you would not get banned from AniDB.

**Comment by jmediamanager** [comment]
You can't get a list of files for a group unfortunately.
That would also be a huge amount of data, which runs into limitations on the UDP api

**Comment by maxpiva** [comment]
Doh. i'm missing something? 

First, we only search for anime, with the tag waiting for bluray completition. Schedule this like every week or every 15 days.

foreach anime in bluraycompletion
{
       we have animeid
      completition_state = 3 (Complete)
       GROUPSTATUS aid={int animeid}[&state={int completion_state}]

      foreach(group in GroupSTATUS result)
     {
FILE aid={int4 anime id}&gid={int4 group id}&epno={int4 episode number}&fmask={hexstr fmask}&amask={hexstr amask}

we have animeid 
we loop gid (from grpstats)
we have epno (the final one)

on results we check for bluray result on quality.

}
}

If you follow 20 animes. it'll be like 150-200 calls depending on the finishing groups (~5)

**Comment by maxpiva** [comment]
I propose a modification of CustomTags adding:

IsSystemTag (User is unable to delete it)
Action (Method Call Action)
LastActionRunDateTime


Example action could be

CheckForBluRayAction in WaitingForBluRayCompletition tag.

CheckForBluRayAction will check if there is bluray available, if not do nothing, if true,will change the anime customTag from (WaitingForBluRayCompletion) to (BluRayAvailable).

BluRayCompleteAction in BlurayAvailable tag

BluRayCompleteAction will check if all your collected episodes are in bluray format.
if true, will remove the Bluray available tag from the anime.

This will generate a kind of autopilot. :)

**Comment by jmediamanager** [comment]
Ok, what you say will probably work, but what you described doing is what Ommina has warned me against.
It would usually be considered leeching, but I will post on AniDB, and see whether it will be allowed or not.

1 - I think with the FILE command it should actually be looking at Episode 1, rather than the last episode since we want to know when a group has starting releasing a certain quality
2 - the GROUPSTATUS command is not very reliable, it actually truncates data if it cannot fit the information into one UDP packet.

Regarding the new table (CustomTagAnimeNotes), I think we can probably generalise this into a generic Notifications table to cater for other types of notifications that the user needs to acknowledge etc.

I also think that the some of the fields that you have added to CustomTag probably belong in a new table, although 'IsSystemTag' is something we should definitely add.

I'll think about it a propose some schema changes here

**Comment by maxpiva** [comment]
Yes, you right, better expand ScheduleUpdate, to store metadata and support per example caching group qualities etc. And trigger this actions from there.

Anyway, I don't think ~150 calls per week, is too much, if it's executed with the correct AniDB timeout, I read the Omnias posts, I think Omnia was referring to scan your whole anime collection searching for groups with bluray releases. Just importing a full season anime, probably generate the same amount of calls.

**Comment by jmediamanager** [comment]
Yup I will get confirmation first just in case.
Don't want to spend too much time on something we won't be able to use.

**Comment by bigretromike** [comment]
If I recall VideoQuality was added some time ago. Do we even use Schedule ? @maxpiva @da3dsoul

**Comment by da3dsoul** [comment]
That's not related at all. This is for when Blu Ray is out, but you don't have it, video quality is what you have

**Comment by ElementalCrisis** [comment]
Its worth talking with AniDB about this again and seeing if we can find a middle ground. I'll leave that up to you @da3dsoul :)

**Comment by da3dsoul** [comment]
Nah. I think we're better off finding another source for that info.

**Comment by bigretromike** [comment]
oh right. I was thinking more about "there is a br-rip" but yeah. this is totaly 3rd party thing

**Comment by ElementalCrisis** [comment]
Current idea is to use our own WebCache to store the info.

**Comment by ElementalCrisis** [comment]
Not currently possible with AniDB.
