### ISSUE TITLE
v3 API Series Search Failing with Japanese Search Queries

### ISSUE THREAD

**Issue by natyusha** [ShokoAnime/ShokoServer#1141]
## VERSION INFORMATION

Server Version: Latest Daily

Desktop Version: N/A

## LOG FILE

N/A

## DESCRIPTION

Utilizing the v3 API to search for anime titles in Japanese yields no results using the `v3/Series/Search` and `v3/Series/AniDB/Search` endpoints.

Edit: Thanks to re: vam it has been clarified that this is caused by not having Japanese in the series title language preference. So I'm not sure if this would still be considered a bug or not.

## STEPS TO REPRODUCE

Using Chihayafuru (ちはやふる) as an example in swagger the issue can be seen:
`http://192.168.1.99:8111/api/v3/Series/Search?query=%E3%81%A1%E3%81%AF%E3%82%84%E3%81%B5%E3%82%8B&fuzzy=false&limit=10`
![firefox_2024-07-08_14-03-49](https://github.com/ShokoAnime/ShokoServer/assets/985941/b81cbb03-c539-4f09-93ce-2f4a15178611)

Some other endpoints seem to work with the same query:
`http://192.168.1.99:8111/api/v3/Series/StartsWith/%E3%81%A1%E3%81%AF%E3%82%84%E3%81%B5%E3%82%8B?limit=2147483647`
![firefox_2024-07-08_14-04-22](https://github.com/ShokoAnime/ShokoServer/assets/985941/e733e33d-8a7b-4ae4-b633-75e30f2d60c3)

**Comment by revam** [comment]
Fixed in daily a while ago. It will only work to search for japanese (be it kanji or kana) if Japanese is in your title preference **for all the APIs**.
![image](https://github.com/ShokoAnime/ShokoServer/assets/7761729/5255a5de-0656-40d8-9e58-3ddf0f6a8ac3)
![image](https://github.com/ShokoAnime/ShokoServer/assets/7761729/379f15d8-6676-4851-81e0-23c5c8187f89)
