### ISSUE TITLE
Reading Chapters of video file throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by Rand-Random** [ShokoAnime/ShokoServer#1174]
This image should show all the necessary info for this bug
![{9C356CCD-EFBC-469E-A16F-121339B36D94}](https://github.com/user-attachments/assets/129c2030-6fa8-4386-8560-db60ab285bdf)

this line: https://github.com/ShokoAnime/Shoko.Models/blob/0712cd1c3953af6fb331b67d7a14ee1cfe7c8d2c/MediaInfo/MediaContainer.cs#L146

Should `value` be used instead of `key`?
`key` contains "Encoded_Date" while `value` actually contains a `DateTime`.
Though the code `var list = key[1..].Split('_');` would nontheless not result in an array of 4 elements and it would still throw the IndexOutOfRangeException.

But juding from the attampt `TimeSpan.TryParse` the `value` with its `DateTime` seems to be more fitting.

So, I don't know what this code normally expects, but the file in question isn't giving the desired information.

or just check if `list` has the appropriate length.

Update:

Here a screenshot of the values within `menu.extra`
![{54451C20-4967-4188-A0B4-FBAEDE7738C9}](https://github.com/user-attachments/assets/5835b277-0023-4e92-aa8f-af356ca452a2)

Seems to have a mixture of expected values, and unexpected values. [3] to [14] seem to be what the code is looking for. [0] to [2] aren't.

**Comment by harshithmohan** [comment]
@revam @da3dsoul Should we catch the exception and skip whatever fails or should we validate it before hand?
The failed ones are not actually chapters so we don't need them

**Comment by revam** [comment]
@Rand-Random Thanks for the bug report. I forgot to check the min length before using the array.

---

The reason I forgot was because the code that lived in APIv3 was using a deconstruction of the array with a default value if the index would otherwise had been out of bound, and thus I forgot to add the check when I moved the code from the API layer in the server repo to the internals in the  models repo (which doesn't have the deconstruction helper that was used in the APIv3 version). My bad. Sorry.
