### ISSUE TITLE
File hashes: reading from/writing to extended attributes

### ISSUE THREAD

**Issue by eduarrrd** [ShokoAnime/ShokoServer#1204]
## VERSION INFORMATION

Server Version: 5.0.0.60 [(9808915)](https://github.com/ShokoAnime/ShokoServer/compare/9808915...master)

## LOG FILE

N/A

## DESCRIPTION

When using Shoko as a data source, starting the query chain with a file hash (`/File/Hash/*` endpoints) is the most reliable method. However, to do so the file currently needs to be hashed at least twice: by Shoko and by the API client. This is wasteful, especially over the network.

As an alternative I propose for Shoko to
* optionally read the hash from an extended attribute (xattr)
* optionally write the calculated hash into an xattr
* both

This allows for the following workflow
1. Rescan is triggered
2. Shoko does its thing, including the filehashing
3. Shoko does the equivalent of `setfattr -n user.$HASHTYPE -v "$HASHVAL" $FILE`
4. Client does a rescan
5. Client does the equivalent of `getfattr -n user.$HASHTYPE -e hex  $FILE` and finds a value
6. (Client does a `GET /File/Hash/$HASHTYPE` and gets fileid to work with)

Same idea idea vice-versa.

### FAQ

* Why even *store* a hash? Allows the client to forgo maintaining a database allow for batch-like, stateless operation. Idempotent.
* Why not have the client look up by path? Path prefixes are different between client and Shoko due to network mounts, in addition file *names* may be different in the case of SMB and mapchars/mapposix (enabled by default) 
* Why xattr? Attaching the hash to the inode gives nice consistency properties: they are preserved on move/hardlink, can be preserved on copy, are transparent to symlinks, and are deleted on delete. No risk of forgetting to deal with a "sidecar file" e.g. moving/renameing one by not the other.
* Is it always consistent? No, a normal write to the file will not update the xattr. Given these are video files this is not a that likely. Even if, e.g. for the force-default audio/subtitle scripts, this could be considered a benefit, given there won't be a DB entry for the updated hash.

## STEPS TO REPRODUCE

N/A

**Comment by da3dsoul** [comment]
What are you talking about? Hash twice? Are you referring to AVDump? That isn't ours. We can't pass data to it. That's kind of the point of it.

**Comment by da3dsoul** [comment]
I misread. I don't understand the point, though

**Comment by Cazzar** [comment]
What issue are you particularly trying to solve that requires the double hashing that you mention in the original issue?

Since I have a few concerns about this approach, particularly being very linux-specific and it is not particularly that portable across OS platforms that we support.

The reason @da3dsoul might have brought AVDump into the question is because that's the only use case within Shoko's code & supported tooling that would cause a file to be hashed a second time, outside of requesting a new hashing operation on an unrecognised file.

Alternatively, we are slowly building on a plugin API that exposes events such as `FileHashed` which would allow you to create a plugin that does this on your own, see: https://github.com/ShokoAnime/ShokoServer/blob/1f19d95419a82a69194e4fe01fdf5ab09eda7139/Shoko.Plugin.Abstractions/IShokoEventHandler.cs#L25 and you can see a working plugin that one person has done here: https://github.com/fearnlj01/WebhookDump-ShokoPlugin

**Comment by bigretromike** [comment]
Hash information about file was always included in database (or if you are old-school like me in file name of given file). Storing it in extended attributes is fine idea, but as mention before not as portable. 
Hash are compute as soon as you add the file to shoko, because without it shoko wouldn't be able to find proper AniDB record.

**Comment by maxpiva** [comment]
I already did go to this rabbit hole. ;). When I was pursing the cloud filesystem support for Shoko, since download the whole file for hashing, was indeed costly...

Deep in Shoko, probably before the Command Refactor, and the WPF Server exists.

 There was a file checker that leverage that Shoko maintains in their database the ED2K, MD5 and SHA1 of every file, it was uses probably only by me to check all the files health. ;)

You could use that as a base, to create your own tool, that connect to Shoko database and write the desire video.xattr files or videofolder.xattr or  NTFS alternate file stream which such data. 

You could in the future leverage what @Cazzar  is talking about, and create a plugin that leverages the FileHash event and write such file, every time Shoko sees a new file and hash it.

Shoko, maintains a mapping between name and the file in db, so moving the file to other folder, will not trigger the hashing again.

**Comment by maxpiva** [comment]
> 
> This is useful to know, thanks. What happens if files have the same name, e.g. `trailer.mp4`? Is there disambiguation? Or are moves undetected? Or something like "at most one file among files with the same name can move between scans"?
> 
Filesize is also stored, both are checked against, to bypass a new Hash Calculation.
Table Filenamehash.

I think also renamers touch this table, in that case, in the import you rename the filename. Both filenames are stored. (But I'm not sure at the moment).


> 
> This is approximately my use case I wrote a tool to go from "arbitrary unstructured files" to something long the lines of
> 
> ```
> by-name -> .by-name-20241201/
> .by-name-20241201/
>   Show1Title/            # new directory generated using Shoko data
>     tvshow.nfo           # new file generated using Shoko data
>     poster.jpg           # new file generated using Shoko data
>     S0E3 Other Title.ext # hardlinked from /some/path/randomname_special_thing.ext, name generated using Shoko data
>     S0E3 Other Title.nfo # new file generated using Shoko data
>     S1EY Title.ext       # hardlinked from /some/path/randomname S12EY.ext, name generated using Shoko data
>     S1EY Title.nfo       # new file generated using Shoko data
>   Show2Title/
>     ...
>   ...
> .by-name-20241130/
>    ...
> ```

Nice, it seems Kodi support multiepisodes nfo in the tvshow, idk others.

**Comment by Cazzar** [comment]
To give a final decision on this:

We are not going to implement this into the core of Shoko as it is out of scope for the project itself and as prior discussed it seems to be for a very specific use case.

If you would like to implement this yourself, the answer of the Plugin API has been provided, though also looking at the swagger endpoints might also provide you some information as well.
