### ISSUE TITLE
JMM Not Scanning Sub-Folders On Networked Drive

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer#338]
As reported by Shadow Kamui on Discord, JMM will scan an import folder that's on a networked drive, but will not scan any of the sub-folders within in it or sub-folders within sub-folders.

**Comment by bigretromike** [comment]
We are talking about mapped network drive?

**Comment by maxpiva** [comment]
Code says, no way:

`string[] files = Directory.GetFiles(evt.FullPath, "*.*", SearchOption.AllDirectories);`

A) The files in that directory, are not in AniDB.
B) JMMServer have no read access to the directory.

**Comment by Stonedestroyer** [comment]
I talked to this user, the problem seems to be he/she can add a drive fine, but it starts to occur when you watch a folder, for example if he does a manual import it will work. But jmmserver won't be able to detect if there is a new file on the watchfolder inside a subfolder, for example

If I were to add

\\NAS\anime
It would detect all files in there but not in the folders when new files are added, this only impacts the subfolders on watch and not on import.

Checking the users subfolder I made sure the permission were the same and they were, 


icacls utility
`\IP\Hostname\Anime\O\One Piece
user1:(I)(OI)(CI)(N)
user2:(I)(OI)(CI)(N)
user3:(I)(OI)(CI)(F)
user4:(I)(OI)(CI)(M,DC)`

`\IP\Hostname\Anime
User1:(I)(OI)(CI)(N)
User2:(I)(OI)(CI)(N)
User3:(I)(OI)(CI)(F)
User4:(I)(OI)(CI)(M,DC)`

IP and user have been redacted due to privacy reasons.

**Comment by RickDB** [comment]
Should be solved with above commit, basically what can happen with UNC is:

- You run out of buffer space
- Event is different then it expects (changed vs created)

This new code will handle multiple events and has better logic, use it for my own project and works well with local and UNC including subfolders.

**Comment by hidden4003** [comment]
that's where it fails:
https://github.com/japanesemediamanager/jmmserver/blob/master/JMMServer/Importer.cs#L256

fileName is "Z:\\Ecchi-Pack\\Astarotte no Omocha! EX\\[Morai-Subs] Astarotte no Omocha EX - OVA [BF8EB403].mp4"
but key is stored as Z:\Ecchi-Pack\Astarotte no Omocha! EX\[Morai-Subs] Astarotte no Omocha EX - OVA [BF8EB403].mp4

**Comment by da3dsoul** [comment]
Can some people test this? I don't have any network drives, as my jmm server computer has the array 'inside', with wires connecting to another tower.

**Comment by da3dsoul** [comment]
No one's complained about this in awhile. I'll assume it's fixed

**Comment by shadowkamui** [comment]
The problem still there

**Comment by ElementalCrisis** [comment]
I'll reopen but it's entirely possible @shadowkamui that this is a unique problem only for you as everyone else using a NAS does not have this problem.

**Comment by shadowkamui** [comment]
@ElementalCrisis I know theirs a possibility I am asking on the synology forums and waiting for staticanime to do some testing because he has a synology to

**Comment by ElementalCrisis** [comment]
Any update @shadowkamui?

**Comment by shadowkamui** [comment]
still not working at this point I will probably change my folder structure xD

**Comment by ElementalCrisis** [comment]
Keep us updated as it seems you're the only one still having issues.

**Comment by bigretromike** [comment]
@ElementalCrisis time to close, right ?

**Comment by ElementalCrisis** [comment]
Yeah, edge case that was either inadvertently fixed or user error.
