### ISSUE TITLE
Add support to Shana Project

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#54]
**Reported by oxytotem, Mar 24, 2013**

http://www.shanaproject.com/

Shanaproject seems to index Tokyotosho and have automatic rss feeds on your shows preferences, that, can be used to automate download all your favorite shows.

**Comment by bigretromike** [comment]
As this is from 2013 its hard to ask but how do you guys think this should be integrated? as search or how...

The alternative version to support those site without realy support those would be add fake tab that would act as preconfigured webpage loader that you would set url and have access to it. as it work same as webpage cookies/logins will work fine so with this one I would see it as RSS page loaded in fake tab and browser it.
Or do we read rss and notify when new entry is there ?

**Comment by AreFinstad** [comment]
i know the dev of shana contacted us back then when we mentioned him. 
he said that we should shout if we ever need anything to get functions working.

personally i think people should use Shana if they dont already.
having a easy way to use it from within JMM would be nice.
edit what we sub on, maybe figure out a way to show all the files of an episode for manual download for example.

ofc a browser would be the simplest.

im sure the shana dev is still willing as he is still active i believe. 
(cant find the issue the shana dev contacted us on, weird)

**Comment by ElementalCrisis** [comment]
No browser/fake tab, at that point might as well just make it a link they click. The best solution would be one that integrates it into JMM Desktop but I'm gonna say we hold off on any potential solution until after the new Desktop UI. First the way JMM Desktop handles downloads need work but it would be pointless to do any work on visually improving on it at the time. 

The underlying code can be added if someone wanted to do this but the XAML part would have to be rewritten which seems like a waste of time when we have other pressing issues to address.

**Comment by bigretromike** [comment]
@AreFinstad good news ! Also I never used shana before - need to look it up and maybe figure out how to integrate it. Also it probably end up on server side as same as reading news from jmm page etc. 

Link to click is even worst idea than fake-tab-browser imo.

Also It could be a good start to make JMMD use API instead of BlobService; 

Need to look this page up

**Comment by ElementalCrisis** [comment]
I know, that's why I was comparing it to a browser/fake tab integration. 

I don't think this should be in Server, the settings should be in Server similar to how it currently is for BakaBt and AnimeBytes but we should follow the already established route and that's in Desktop with the other torrent providers. 

The goal of Server is to manage your local collection, it's why we're adding select utilities into Server Web UI to help do that. Expanding your collection is not the goal of JMM Server, that's one of the goals of JMM Desktop and we need to make sure we're sticking to the already established boundaries.

**Comment by bigretromike** [comment]
You remamber that we are moving function out of jmmd to jmms right? I see this on server side then you could use it with notifications etc 

On October 6, 2016 11:15:16 PM GMT+02:00, ElementalCrisis <notifications@github.com> wrote:
>I know, that's why I was comparing it to a browser/fake tab
>integration. 
>
>I don't think this should be in Server, the settings should be in
>Server similar to how it currently is for BakaBt and AnimeBytes but we
>should follow the already established route and that's in Desktop with
>the other torrent providers. 
>
>The goal of Server is to manage your local collection, it's why we're
>adding select utilities into Server Web UI to help do that. Expanding
>your collection is not the goal of JMM Server, that's one of the goals
>of JMM Desktop and we need to make sure we're sticking to the already
>established boundaries. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/54#issuecomment-252090905

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ElementalCrisis** [comment]
We're moving settings out of Desktop and possibly providing access to some of the utilities depending on restrictions. We never agreed on removing functions, in fact that last talk related to functions was the idea of removing various functions completely like Downloads and offering them as plugins to Desktop.  Server is the back-end, it's supposed to be lightweight and for running your collection, not managing it nor adding to it. That's why we have Desktop which is the front-end and provides all the services Server does not. 

However before we get into this conversation again, as previously stated Downloads in general and how we currently utilize it needs to be rethought but this is a conversation for another time. At the moment we should focus on 3.7, assessing the issues attached to the milestone and preparing for the beta that's around the corner.

**Comment by bigretromike** [comment]
I remamber about plugin system - im fine with it.
You said "Server is the back-end, it's supposed to be lightweight and for running your collection, not managing it nor adding to it."
IMO:
1. its not true as you can add importfolder before and now via server so you add and remove to/from collection
2. jmmd should not be essential to user bacis jmmserver functionality - yes, it should be expanded and have wider functionality (which dons't mean that those option should be on client side only - some should be on server side with usable only in jmmclient)
3. Functionality like download - it all depend you could leave some in server also - or make plugin system for server: user case: couchpotato/sonarr alike usage inside jmmserver as server will run more ofthen if not 24/7 than client - but thats just an idea.
4. JMM Desktop if its front-end as you mention should be only front-end so functionality should go to back-end :-)

And yes, that for another time.

We must give our best for beta! Its time :+1:

**Comment by bigretromike** [comment]
From what I remamber this is no-go as ShanaProject didn't want to colaborate, also torrent are dead here, right ? @ElementalCrisis

**Comment by da3dsoul** [comment]
Correct

**Comment by ElementalCrisis** [comment]
Someone else can create a plugin down the road and add download functionality back in but we no longer officially support it.
