### ISSUE TITLE
give out all images in api.

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#631]
coming from https://github.com/Cazzar/ShokoMetadata.bundle/issues/9
we need the Shoko server API to support giving out all the images the server has. 

right now it gives out only one cover and one fanart i believe. giving the api users (plex metadata) few choices compared to the rest.

**Comment by bigretromike** [comment]
Its good idea, but im it would need to have a proper `tag` so the plugin/addon developer can pick if he want to wait longer for all images to get listed or not. because it would be a bad idea by default to throw all images for filters like `All` and it would be silly just to throw all images just for serie when you already inside it.

**Comment by bigretromike** [comment]
This should give developer option to pick `allpic`, number of `pic` or default is back-compatible which is 1 for fanart and 1 for banner.

**Comment by Cazzar** [comment]
`allpics=1` doesn't seem to load all posters.

**Comment by Cazzar** [comment]
![image](https://user-images.githubusercontent.com/994214/29126025-a24ea174-7d60-11e7-9386-be124aa84f74.png)

**Comment by Cazzar** [comment]
https://github.com/ShokoAnime/ShokoServer/commit/425e6ea3801c3708c00d7d0cd27158d68509e5c2
