### ISSUE TITLE
Rename Utility cannot change directories

### ISSUE THREAD

**Issue by Cazzar** [ShokoAnime/ShokoServer#643]
When using the rename utility in desktop it does not call `IRenamer.GetDestinationFolder(SVR_VideoLocal_Place video)` to see if there is a differing location that it should be at.

Implementation:
https://github.com/ShokoAnime/ShokoServer/blob/master/Shoko.Server/API/v1/Implementations/ShokoServiceImplementation/ShokoServiceImplementation_Utilities.cs#L454

We should either add the option to rename only filename, or include possibly moving.

**Comment by da3dsoul** [comment]
Hmm.... I'll save it due to the fact that I will need to completely rewrite that for #504. There's a lot I'll need to do for Desktop. I could look into making it move if required, but considering the current system doesn't allow changing the destination, it seems pointless unless someone like you compiles a custom renamer implementation

**Comment by Cazzar** [comment]
In the long run it'll be nessicary. And I only added this for the factor of
it being an extension of #504

**Comment by da3dsoul** [comment]
True, for now I could just make it rename and move if required

**Comment by Cazzar** [comment]
https://github.com/ShokoAnime/ShokoServer/commit/9699d5fd2fca0d407f15aaa7cf609ad2862022fe
https://github.com/ShokoAnime/ShokoDesktop/commit/331daa637c122ed2d3f9a1c073c273fc399bec0c
