### ISSUE TITLE
Contracts are not Updated for Updated Anime Info

### ISSUE THREAD

**Issue by Baine** [ShokoAnime/ShokoServer#734]
## VERSION INFORMATION

Server Version: 
27914e13e6882cfd4cb1e58b3347dc4f944aa3ec

Desktop Version: 
2cb9bee4d334899832647d175a114a4bbdb31d4c

## DESCRIPTION

Desktop fails to show the correct episode count or episode names after a show is updated by new info from anidb.

## STEPS TO REPRODUCE

1. Have currently airing show whose data hasn't finalized on anidb yet (e.g. Black Clover (2017))
2. Check it's episode count and names after server pulls new info for that one

**Comment by Baine** [comment]
@da3dsoul the update only works partially :(
as soon as the server is restarted, the updated info is lost
i.e. anime caligula, shows "episode x" after (and including) episode 5.
refresh the anidb info and update the views shows the correct episode titles.
restarting the desktop retains those titles
after restarting the server, the titles are back to "episode x"

**Comment by Baine** [comment]
to add additional info:
if a series is updated because it was changed on anidb (as shoko regularly fetches updated anime info), the information persists.
example:
gundam build divers.
used to show "episode x" all the way except for ep one.
right now ep 13 also has a correct title, which was added to anidb on 27.06.2018 00:30 (GMT+1).
this title also sticks when the server is restarted.

**Comment by da3dsoul** [comment]
Can you reword this? I don't understand.
You say "updated"
There's Anime Updates, this happens when you click Update in the series view and it happens when a series is changed on AniDB
There's File Updates, this generally only happens when you import or trigger it manually via the fully expanded episode view
There's TvDB Updates, this happens from many scenarios, but mostly auto-updates and when a series is linked

Titles can come from TvDB and AniDB. I need to know exactly which updates are having issues.

**Comment by ElementalCrisis** [comment]
@Baine still an issue?

**Comment by bigretromike** [comment]
weren't contracts like very old concept that shouldn't be used anyway thanks to api ?

**Comment by da3dsoul** [comment]
Yeah. I've gotten rid of a lot of them and their usage. Still WIP
