### ISSUE TITLE
[Proposal] Renamer alternatives

### ISSUE THREAD

**Issue by Cazzar** [ShokoAnime/ShokoServer#766]
This is an idea which would likely be implemented only in API and in Desktop v2

Allowing someone to set up the renamer via a ordered preference in the case where one renamer fails (for any reason) or gives a null result, we should allow the fallback to another renamer.

Ex:
1. Custom Renamer 
2. Legacy Renamer

**Comment by da3dsoul** [comment]
It's doable for sure, but I could see that being nothing but annoying, unless you intentionally throw a failure to go to the next renamer.

**Comment by Vesnyx** [comment]
This suggestion seems quite weird to me. Wouldn't it be better to have one stable renamer instead of this? Perhaps instead of defaulting onto the legacy renamer, have a tab similar to the Unrecognized ones that catch this and allow the user to fix their script?

**Comment by Cazzar** [comment]
@Vesnyx Modularity would be one argument.
Say you want to have a format for TV, Hentai and Movies each unique in it's own.
Having a single renamer having all that branching logic would have a high cyclomatic complexity.

**Comment by Cazzar** [comment]
Also further to this, we wouldn't surpress any errors, and the "Fallback on error" argument was an example, it would be a better design choice of explicitly failing to go to the next renamer option.

**Comment by Vesnyx** [comment]
Perhaps a different implementation of the current script method could be used? There's already a way of differentiating naming conventions based on the received results:
```
// Episode Number, don't use episode number for movies
IF T(!Movie) DO ADD '- %enr'

// Video Source (only if blu-ray or DVD)
IF R(DVD) DO ADD ' %src'
IF R(Blu-ray) DO ADD ' BD'
```

> Having a single renamer having all that branching logic would have a high cyclomatic complexity.

If I am understanding this properly, the cyclomatic complexity would simply be moved from inside the script to outside where instead of having "if" checks inside, they would be outside, which is probably easier for the end-user to understand. 

Next, how would we go about separating the number of alternatives provided? Would we be allowing the user to generate as many as they would like? Would there be predefined naming script files for each type (Movie, Episode, etc.)?

Perhaps the issue should be renamed to "Modular Renaming Schema" instead.

**Comment by Cazzar** [comment]
The current scripting system is going to be replaced with a new system entirely, most of the backend work is done, see #504

**Comment by Cazzar** [comment]
If you want to discuss further, might be best to come onto the discord, and I can chat there.

**Comment by Cazzar** [comment]
The new renamer pipeline system in place has put this in effect.
