### ISSUE TITLE
AniDB Mylist watched status reset after re-importing files

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer#770]
## VERSION INFORMATION

Server Version: 3.9.3 ? commit hash 5715c3b91dca7aceaa68ca695bda1752c70563d4
Desktop Version: 3.9.3

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

[2018-12-27-log.txt](https://github.com/ShokoAnime/ShokoServer/files/2724444/2018-12-27-log.txt)

## DESCRIPTION

Watched state got reset in mylist in anidb after re-importing files.

Reset state is 0/12 column.
![image](https://user-images.githubusercontent.com/197087/50648115-06c1b000-0f83-11e9-9354-826923378ae1.png)

Shoko still has correct watched states.
![image](https://user-images.githubusercontent.com/197087/50648078-ef82c280-0f82-11e9-92a3-623bb55c04ed.png)
Auto update settings
![image](https://user-images.githubusercontent.com/197087/50648090-fa3d5780-0f82-11e9-811e-dd1fc5f2c223.png)
AniDB Options
![image](https://user-images.githubusercontent.com/197087/50648463-f52cd800-0f83-11e9-9475-77b513fa0e9f.png)

## STEPS TO REPRODUCE

Move files out.
Run remove missing files.
Move files to drop folder/collection.
Run import.

**Comment by hidden4003** [comment]
Same behavior was reported in 3.9.4 as well.

**Comment by Mik1ll** [comment]
I think this should be high priority, I wiped out quite a few watched states on AniDB without realizing it. Any file with watched status in AniDB is marked unwatched when imported. Possibility of ruining AniDB MyList. Reproducible.

**Comment by Pizz001** [comment]
cheers for passing this info on, but due to my file sizes this may almost be impossible for me to fix, as I have 16tbs of anime to try and move about, it may work if i rename folders but that will screw my network shares up ..but then again redoing shares could be  an easier way, i need to have a think about the best way

question, if i blank a new but empty folder, then rename my full folders to "name1"  then tell it to look at the new empty "name" folder, that should see it as blank ...yeah there should be aby hidden files or anything I need to be on the lookout for 

then run the remove missing files 

once done then rename the folder and delete the empty one 

before the reimport

**Comment by da3dsoul** [comment]
What

**Comment by hidden4003** [comment]
It only happens if you replace release for example, but just rearranging files run import should fix paths and this issue should not trigger.

**Comment by Pizz001** [comment]
> What ? Sorry that English is not doing it for me. The way to avoid this is not running remove missing files.

sorry that's the meds I'm on turns my mind into a goldfish and as it's for 3 discs in my neck replaced twice that control my whole right side inc my hand, even I'll say it can come out a bit odd .. it's ok too lol,  i take no offence as that's classed as good to somethings i've typed :)

**Comment by Pizz001** [comment]
> It only happens if you replace release for example, but just rearranging files run import should fix paths and this issue should not trigger.

I'll try that if I can make space somehow

**Comment by Pizz001** [comment]
anidb found that my problem started on 03/03/2019 , i managed to hope on to discord and give Mik1ll  my log for that day as a zipped file

**Comment by Mik1ll** [comment]
Copying what I wrote while ago in Discord,
https://github.com/ShokoAnime/ShokoServer/blob/a03a9f94def373cb38ab27f238a75ac6e793af9a/Shoko.Server/Commands/AniDB/CommandRequest_AddFileToMyList.cs#L135
Importing files goes here and imported files watchedLocally bool is always false because originalWatchedDate is null. It seem sto me that lines 128 to 147 shouldn't be used for files being added, as the Set Watched (ServerSettings.AniDB_MyList_SetWatched) and Set Unwatched (ServerSettings.AniDB_MyList_SetWatched) are described as manual actions (unless you choose to set watched state on files through the Video player options).
