### ISSUE TITLE
Folder Scan Exclusion

### ISSUE THREAD

**Issue by Urlryn** [ShokoAnime/ShokoServer#837]
Feature request/enhancement:

I am looking to have a shoko/docker config option added that will allow you to specify folder or folders that would be excluded from being scanned.  Or maybe have shoko ignore hidden folders (though this option could be a problem for the anime series .hack) during scanning.

On Unraid there is a plugin that adds a hidden '.Recycle.Bin' folder to hold samba deleted files and will remove the aged files on a schedule. A '.Recycle.Bin' folder is created the first time a file is deleted. 

So in the case of Shoko....if you delete any file via shoko desktop the files would be moved to this .recycle.bin folder.  When the import process runs, while this folder contains these deleted files, it will see this and then re-import those files again.

Urlryn

**Comment by xmodx10** [comment]
+1 for this feature as well. I also use Unraid and the ".Recycle.Bin" always causes me grief with Shoko, having to disable the folder watch to work around it every time is a pain.

**Comment by Cazzar** [comment]
I spoke to @Urlryn about this issue beforehand, the best way we could do this is extend https://github.com/ShokoAnime/ShokoServer/blob/3144926b262ff00db253c21686f636c0f4e27510/Shoko.Server/Import/Importer.cs#L274 to be a array (maybe also regex) check instead of a hard-coded string, defaulting to that.
