### ISSUE TITLE
Consider using communication channels other than Discord

### ISSUE THREAD

**Issue by lsahnicne** [ShokoAnime/ShokoServer#938]
﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.

https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop **LOG FILE**. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below **MUST BE USED** when submitting an issue, no exceptions.

## VERSION INFORMATION

Server Version: 4.1.2.0

Desktop Version: -

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

-

## DESCRIPTION

I apologize for not following the very first guideline in the template i am filling right now, but as i will explain below, the matter of an issue i am having prevents me from doing so. During the first run setup of a Shoko server i failed to guess what functionality some of the options in the Community Sites section provide and was looking to seek an advice as the corresponding [documentation page](https://docs.shokoanime.com/server/setup/) lacks the needed description. The only contact information i've found on your website was a link to a Discord server. Having had access to that platform permanently restricted for not complying with the requirement to provide my phone number, i see no other way to reach out but submitting this issue here on GitHub. For the sake of users who may find themselves in the same situation as myself, or those who simply do not find Discord's Terms of Service and Privacy Policy to be acceptable, I ask you to consider allowing to contact you using more open communication channels, like IRC, Matrix or e-mail.

## STEPS TO REPRODUCE

-

**Comment by da3dsoul** [comment]
Well...no, I just hate irc and its derivatives. I agree discord is bad, but switching chat services is no easy feat. It requires convincing the thousands of members to go with you, which isn't happening.
I'm not sure what you mean about the phone number thing. Our server doesn't require the phone number verification for users. Afaik it's just a step for spam mitigation.

But! As for email, posting on GitHub will just email several of us.

**Comment by da3dsoul** [comment]
PS. The issue template is a guideline, not a rule. You can just Ctrl+A delete if it's not valid for the type of communication you are trying for. I've done it here, for other communities, and believe the only reason it should be always adhered to is if it's being scraped into another issue tracker. In the case of most public projects, that's not likely.

**Comment by lsahnicne** [comment]
"Switching chat services" and moving an entire community to a different platform is not what i am asking here. You can have one contact method available alongside others just like you can run multiple chat applications at the same time.
Posting an issue on GitHub is quite a roundabout way to e-mail someone and I, for example, would have reservations about using the Issue section of GitHub as a support forum because as far as I know it is not intended for such use.
As for the "phone number thing", what I mean is one day, out of the blue, instead of a usual Discord application window I was greeted by a screen saying "verification required" with the only option to verify an account being entering a code from the SMS message sent to a phone number. According to their support, Discord's "detection system has triggered successfully" and my account, as well as new ones i might register, would remain locked until verified using phone number. I've seen numerous reports of the same thing happening to other users in /r/discordapp so it appears i was not the only victim of such false positives.

**Comment by Cazzar** [comment]
The problem is while yes, we could look at having additional channels, all of us doing any help with the project are also doing this in our spare time.

Myself I know I won't really check on IRC/Matrix, I only typically check the discord as other communities that I frequent and chat with people there use Discord as well

IRC, I used to frequent, though while going through things, in the typical support fashion it would make it simply harder to help users, as it has no compatibility with direct file uploads (images/text) and zero chat history.

Matrix, I continue to stand by my comments saying that for the general user that will need support, it seems way too complicated to set up with the mess of steps required and the literal application feature support matrix that turns out to be a mess.

Email, not to mention how much it will just get spammed with it being publicly listed as any emails these days will be, there are massive security risks involved with it, since it would have to be a shared email inbox, or a forward, exposing email addresses of people directly, which, I know for one, I wouldn't want at all.

Alternatively, Github does also have a "Discussions" form, if you don't want to use issues, which you can access in the tabs up the top, or here: https://github.com/ShokoAnime/ShokoServer/discussions

**Comment by da3dsoul** [comment]
Interesting, I had not heard of these account locks. That is unfortunate.
Yeah, like cazzar said, the biggest problem with having another point of contact is that we'd need to remember to check it. I have no reason to use anything else until discord becomes truly unusable. I only use GitHub because they email me and they store our version control and release pipelines.

I agree that discord has problems, but despite those issues, it serves us well. Most people already use discord, so there's a low barrier to entry, as well. One of the biggest reasons I don't seek help in certain communities is that my options are IRC or get fucked, and I'm not sitting in IRC for a day waiting for someone unless I really need help. By that time, I'm already mad, and the communication has unnecessary friction.

If you know of actually better options than things like IRC or Matrix, then do advise. With discord 's shady practices, I'm open to looking into other services for my own uses.

**Comment by ElementalCrisis** [comment]
This has been mentioned before as some people are unable to use Discord, like @lsahnicne mentioned. I did look into alternatives like Discourse, but it does create a new problem of us having to maintain and check it. I think for the time being, GitHub will have to suffice and unless Discord goes full Facebook on us, we probably won't be leaving anytime soon.

Revamping Shoko Docs is on my to-do list and will coincide with the new Web UI, we're hoping for an end of the year beta, but we'll see what happens. Feel free to use this issue for any questions you currently have, and we'll answer them.

**Comment by lsahnicne** [comment]
Okay, before i begin dumping my questions here, let me address some of the points you made regarding my original request. Firstly, I don't get the argument about "having to check" those communication channels. Both IRC and Matrix client applications allow setting up notifications for new messages in specific channels or received directly from other users. So all it takes to know about them is having said application run in the background and occasional glance on your system tray. It's not some active process that requires attention and effort on your part. As for the Matrix setup being complicated, i don't recall the onboarding process being much different from Discord. You register an account with your e-mail and then you can join or create a chat room or, as Discord calls them, a "server". The only difficulty a layman might face is choosing an instance, but for the task of joining a room and asking a question, the default matrix.org is sufficient. "Most people" already using Discord is a very subjective statement. I could argue "most people" use WhatsApp. Or facebook. Or Telegram. It all depends on who do you consider to be "most people" in the given context. Although I can't argue that overwhelming majority of users who run Shoko server don't use Discord for i do not possess relevant statistics data, i still find this statement to be narrow-minded. The problem with Discord is not that "some people are unable to use it". It's that it is a very closed, "walled garden" platform that demands users to accept it's Privacy Policy and Terms of Service and run a proprietary client application in order to participate and still reserves the right to kick you out at any given time without disclosing a reason for doing so. Meanwhile, anybody with an access to the Internet is free to connect to an IRC channel using client of their choice without even registering any account.

All right, with that out of they way, now for the questions i have regarding Shoko server:
1. As someone whose use of AniBD's MyList never extended beyond simply importing anime list from MAL i fail to grasp the meaning of all options in the "Mylist options" and "Update Options" sub-sections of "ANIDB" settings section.
1.1. Does "Read watched" option mark series that i have as "completed" in AniDB as watched in Shoko? It doesn't appear to be this way, considering that Dashboard displays only 4 completed series out of 257 indexed so far in "Collection breakdown" section.
1.2. How does "Set watched" work? I see the indexed files appear on AniDB's MyList, but they are not marked as watched. Is there a way to automatically mark these files as watched in case there are already watched generic files in MyList for this series?
1.3. What is the "Delete action"? Is it related to the "Remove Missing Files" action in the actions menu? I don't see any other actions related to deleting something.
1.4. What is the difference between "Sync Mylist" and "Get Mylist stats" options and what they do? Will my AniDB MyList get overwritten by the Shoko if i change these options from "Never" or is it the other way around? 
1.5. Does the "Anime Information" update option loads data from AniDB for all the indexed files from scratch every single time? After the hashing of my files, which in itself took quite some time, there were around 6000 "General commands" or whatever those are in the queue.
![librewolf_EVmXQVEx27](https://user-images.githubusercontent.com/43319094/177429102-42da7f43-7da5-4fcf-88ff-34b5d535c75b.png)
After around a day, both that number and the number of unrecognized files dropped a couple of thousands, but then the number of "commands" jumped back to around 6000. Is it related to the "Update anime information" option? If it just keeps up like this, i'm not sure those files are ever going to be recognized.
2. In the "AniDB Login" section of settings there specified two ports 4556 and 4557. What are they used for? Shouldn't they also be enabled for Shoko server Docker container along with a port 8111?
3. Near the WebUI Version there is a link saying "update available". After i click it i get a notification about installed update and get logged out of console. But after i log back in, the WebUI Verison remains unchanged and the "update available" link stays the same.
4. A description for available actions would be welcome. For example, i have no idea what "Update Series Stats", "Sync hashes", "Recreate all Groups" and many other actions do and i don't want to find out by experimenting out of fear of messing up MyList or having to index and identify my entire collection from scratch again.
5. Same goes for the "breakdown" sections on the Dashboard. What's the difference between "Missing Episodes (Collecting)" and "Missing Episodes (Total)"? Between "multiple files" and "duplicate files"? Can i see the list of those files? Should i care about "Missing TvDB/TMDB Links"? Does "series completed" show a number of series i've watched with Shoko server running or does it sync with MyList? (see 1.1.)
6. How to properly deal with unrecognized files? There is an AvDump option and from what i could gather from AniDB wiki it uploads a hash of an unrecognized file to AniDB and allows to attach it to a releases group there. Should i manually add a release group for every single unrecognized file? What if the initial release was changed by the uploader who added an additional audio/subtitle tracks and therefore are not eligible to be added to a group? Will such series remain unavailable to watch through players connected to Shoko? Anyway, for now trying to AvDump results in  a following error:
> 2022-07-05T23:03:08.5318141Z An error occurred while AVDumping the file "file": System.ComponentModel.Win32Exception (2): No such file or directory at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start() at Shoko.Server.AVDumpHelper.DumpFile(String file) in /usr/src/app/source/Shoko.Server/Utilities/AVDumpHelper.cs:line 171
> 2022-07-05T23:03:15.7610305Z System.Net.Sockets.SocketException (110): Connection timed out at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP) at AniDBAPI.Commands.AniDBUDPCommand.ProcessCommand(Socket& soUDP, IPEndPoint& remoteIpEndPoint, String sessionID, Encoding enc) in /usr/src/app/source/Shoko.Server/AniDB_API/Commands/AniDBUDPCommand.cs:line 39

**Comment by ElementalCrisis** [comment]
My information might be outdated as a lot has changed but this is how everything was intended to work years ago. 

1.1 
Both "Read Watched" and "Read Unwatched" pull watch state data for AniDB. I recommend unchecking both "Local Actions" options and running the "Sync AniDB MyList" action to have Shoko pull in your watched data. Please note, the series has to already exist in your Shoko library before running this command, it will not create an empty series for you. Make sure to re-check the "Local Actions" once done so any changes made in Shoko will also get made on AniDB. 

Please note that checking the wrong options can cause unreversible damage to your AniDB MyList options so always double-check these settings before running the "Sync AniDB MyList" action.

1.2 
Both "Set Watched" and "Set Unwatched" send AniDB the watched state data for the series in your collection. This is done once the file is marked as watched by Shoko. 

This doesn't seem to be working as intended, created an issue. 
#942 

1.3
No, the "Delete Action" is for setting the state of a deleted item. You can have Shoko remove it from your AniDB list, have it removed only from your database, have it mark the file as deleted, remote or external or mark it as unknown.

Information on the AniDB specific options.
https://wiki.anidb.net/Filestates#deleted

1.4 
"Automatically Sync MyList" information means that depending on your MyList Sync settings, Shoko will pull your MyList data from AniDB and update it with any changes in Shoko that are not on AniDB. I don't remember the order so @da3dsoul could you please comment on that, I know you've worked on it before. 

"Automatically Get MyList Stats From AniDB" ignores Shoko and just pulls data from AniDB, meaning watched states in Shoko only will be overwritten by what AniDB has. Additionally, series in Shoko but not on AniDB will not have the series added to your collection nor their watched states uploaded. 

1.5 
This is normal as hashing is just one part of the process. Series metadata from AniDB and TVDB are downloaded which is why you'll see your queue count rise as files are hashed. The screenshot you posted shows you have no files waiting to be hashed, that's what the first count is for. 

2.
These are the ports used by AniDB, 4556 is for AniDB itself and 4557 is for AVDump. I don't know if they can be changed as that's more @Cazzar & @da3dsoul area. 

3.
This should be fixed now, might need to have it "download" again and do a hard refresh, CTRL+F5.

4.
They are pretty self-explanatory. 

**Update Series Stats**
Updates the series states, pulls the latest information for that series from AniDB. 

**Sync hashes**
This is old and more for when we supported cloud import folders but would make sure the hashes in your database match the file hashes on the cloud import folder. 

**Recreate all Groups** 
Recreates all groups which is useful if a show was imported out of order, for example, Naruto Shippuden than Naruto. As Naruto is the "parent" of that series grouping, running the command would fix it by re-creating the group and make the group Naruto instead of Naruto Shippuden. There are options to change how grouping works and the option to disable grouping altogether. 

5.
Shoko has been around for a long time and back in the old days, people would only download releases from their preferred fansub groups. So, if you were collecting say Bleach from group XYZ and they hadn't released the latest episode, but group ABC had, your "Missing Episodes (Collecting)" would still show 0 but "Missing Episodes (Total)" would show 1. 

This is something we removed in the upcoming Web UI as fansub groups are all but dead. 

Mutiple files means you have multiple files for a particular episode, say 720p and 1080p releases. Duplicate files mean's you literally have the same file twice in your collection, probably just named differently. 

Without a proper TVDB/TMDB link, Shoko is unable to pull metadata for that series meaning data is missing. This data is usually used by the HTPC plugins like ShokoMetadata (Plex). 

Multiple & Duplicate Files and TVDB/TMDB linking can only be accessed via Shoko Desktop for now, eventually you'll be able to manage them via the Web UI but that is down the road. 

6.
You can dump the file via the Web UII and then add the release on AniDB. 

This guide is pretty detailed and you can follow it, you can skip the parts about actually using AVDump2 as that process is done when you click the dump button in the Web UI.

https://yukisubs.wordpress.com/guides/tutorial-updating-anidb-with-avdump2/

As for the error, that is more @da3dsoul and @Cazzar area.

**Comment by lsahnicne** [comment]
> **1.5** This is normal as hashing is just one part of the process. Series metadata from AniDB and TVDB are downloaded which is why you'll see your queue count rise as files are hashed. The screenshot you posted shows you have no files waiting to be hashed, that's what the first count is for.

That's not quite what i was asking. Please read my initial question again. I see the second number rising occasionally without the first number going above zero. Considering I didn't add any new files to the monitored folders, is Shoko grabbing the metadata for the already hashed files again and again? Is "automatically update anime and episode information" option responsible for this behavior?

> **2.** These are the ports used by AniDB, 4556 is for AniDB itself and 4557 is for AVDump. I don't know if they can be changed as that's more @Cazzar & @da3dsoul area.

Changing those port numbers isn't what I'm concerned about. It's that the [installation guide](https://docs.shokoanime.com/server/install/) only makes the Web UI port 8111 available for Shoko server Docker container. Therefore i assume that the ports set in the settings for AniDB and AVDump would simply be inaccessible from outside. As far as I can tell, in order to function correctly not only these ports should be published in Docker, but also forwarded on my router.

For now, I've installed Shoko Desktop to access the control functions not available through Web UI. I need to deal with thousands of unrecognized files that I have. Looking at the Utilities - Unrecognized section of Shoko Desktop, I assume it is not necessary to dump the file to AniDB but I can assign what file belongs to what series(group) locally. Going to have to wait until the AniDB Queue clears first though, otherwise i don't seem to be able to add new groups because of AniDB ban. Hope it won't start updating everything from the scratch again now that I've set the aforementioned setting to "never".

**Comment by ElementalCrisis** [comment]
> > **1.5** This is normal as hashing is just one part of the process. Series metadata from AniDB and TVDB are downloaded which is why you'll see your queue count rise as files are hashed. The screenshot you posted shows you have no files waiting to be hashed, that's what the first count is for.
> 
> That's not quite what i was asking. Please read my initial question again. I see the second number rising occasionally without the first number going above zero. Considering I didn't add any new files to the monitored folders, is Shoko grabbing the metadata for the already hashed files again and again? Is "automatically update anime and episode information" option responsible for this behavior?
> 

It's the general queue, your log will tell you what its downloading. Usually, its updated calendar info and updated series info depending on your settings.

**Comment by revam** [comment]
> It's that the [installation guide](https://docs.shokoanime.com/server/install/) only makes the Web UI port 8111 available for Shoko server Docker container. Therefore i assume that the ports set in the settings for AniDB and AVDump would simply be inaccessible from outside. As far as I can tell, in order to function correctly not only these ports should be published in Docker, but also forwarded on my router.

Iirc then docker is only concerned about listing the ports for **incoming traffic** in the docker file so there is no need to expose the ports **the anidb api server** is listening on (since that would be comsidered **outgoing traffic** for our local instance).

**Comment by revam** [comment]
Your firewall on your server and/or router may interfer with the traffic though, so be sure to check if they're properly set up so the container can communicate over those ports.

**Comment by revam** [comment]
@lsahnicne
6. Set the `AVDUMP_MONO=true` env var for the container. It will download and install the necessary dependencies (the mono runtime) for running avdump2 on linux

https://docs.shokoanime.com/server/install/
![image](https://user-images.githubusercontent.com/7761729/177880373-83b11020-addc-4e6d-9dfe-f9aca9736d0b.png)

**Comment by bigretromike** [comment]
> I need to deal with thousands of unrecognized files that I have. Looking at the Utilities - Unrecognized section of Shoko Desktop, I assume it is not necessary to dump the file to AniDB but I can assign what file belongs to what series(group) locally. 

If those unrecognized files are files you downloaded and not self muxed/riped/encoded and are consider `anime` as AniDB standards go the best thing you could do is adding them to AniDB - its simple few step process: hash them (ed2k), add them with info of group (or not) made them and save. After few minutes AniDB auto aprove them and shoko will recognize them.  And in can of `database wipe` or `fresh start` shoko will handle them thanks to anidb without any need to manually link them.

Sadly not every `anime` is `anime` for AniDB, but then again there is not known better meta file library that does what anidb does.

**Comment by vyressi** [comment]
...you could also get a free DID for discord's authentication by joining google voice
