### ISSUE TITLE
Scan timer for drop folders

### ISSUE THREAD

**Issue by nettosama** [ShokoAnime/ShokoServer#98]
Each import folder should have a rescan timer, that will trigger a scan on that folder for new files. The current option of "Watch for new files" doesn't work on network locations.

**Comment by anzerman** [comment]
:+1:

**Comment by ElementalCrisis** [comment]
Pretty sure this is no longer an issue, @hidden4003 and @da3dsoul can you confirm?

**Comment by da3dsoul** [comment]
We just need better logic in when to use polling. I know there are Network filesystems that don't support watched folders

**Comment by hidden4003** [comment]
Hmm.. it is still an issue, it is made via polling on cloud systems because they don't have the events about file creation. But local system uses file creation event from filesystem so if it somehow missed the event then it will only retry when another file is moved into the folder.

Depending on the circumstances polling might be more resource effective in case of large number of file events, but there is no ideal solution as far as I know, polling would be waste of resources in the long run.

**Comment by revam** [comment]
1. We don't directly support cloud file systems anymore
2. If you have enabled the import to run on a schedule then it will periodically scan any drop sources.
3. Can we close this now? @da3dsoul

**Comment by hidden4003** [comment]
Depends on if file system events are consistent in docker and now we have arm. But if we are dropping the periodic check altogether and going to event based, then this can be closed.

**Comment by revam** [comment]
1. The file system events inside the docker container work just as well as outside the container.
2. I don't think arm has any impact on the file event support.

**Comment by ElementalCrisis** [comment]
Issue no longer relevant, closing.
